### ISSUE TITLE
Importing the library is causing a crash on SSR - non isomorphic

### ISSUE THREAD

**Issue by carlesnunez** [rehooks/local-storage#55]
**The problem**
As this library perform operations on import with CustomEvent api that only works on client importing this on files that are being used from server side is causing a crash.

**Comment by matepaiva** [comment]
Hello :) Are there any plans to fix this issue?

**Comment by jharrilim** [comment]
Yes, https://github.com/rehooks/local-storage/pull/61 should fix it (and fix other scenarios like incognito).

**Comment by matepaiva** [comment]
Thank you!

**Comment by jharrilim** [comment]
It turns out that #61 won't fix this. The main problem is that SSR tools like Gatsby currently don't support anything browser related on the server side. It is unreasonable to expect every browser module to polyfill their module for browser globals since browser code should be expected to run... in the browser.

I am currently working on a pre-rendering tool which solves this problem, because it is definitely possible to be done on the backend instead of trying to fix every browser module. You may see an example here:

https://github.com/jharrilim/rolledup/tree/master/examples/proj

The React code in that "proj" example emits the static HTML found in the "dist" folder.

**Comment by Hubro** [comment]
@jharrilim Can't you do a `if (typeof window === "undefined") { ... }` and make your hook a noop on the server side? Just return the default value and don't do anything more.

I'm a bit less sure about the `CustomEvent`, since you can't subclass a class that doesn't exist on the server side. Could you conditionally define the class?

This issue unfortunately makes this library impossible to use with Next.js, since it has SSR by default :disappointed:

**Comment by carlesnunez** [comment]
I remember that the problem came because the Custom Event was not being able to be extended conditionally so it was always failing because of the extend.

**Comment by Amantel** [comment]
Hey ho! Any luck with this?

**Comment by lorensr** [comment]
One possible solution here: https://github.com/rehooks/local-storage/issues/17#issuecomment-503828746

**Comment by Amantel** [comment]
well... that is to dirty for me, TBH)

**Comment by yovanoc** [comment]
You could use https://github.com/Comandeer/babel-plugin-banner to add `typeof window !== "undefined" &&` in top of the file

**Comment by jharrilim** [comment]
> Hey ho! Any luck with this?

Sorry for the super late response; yes, I believe so. IIRC, The things that are needed to make this work are:

1. `CustomEvent` needs to be conditionally defined (Will be done here https://github.com/rehooks/local-storage/pull/78)
2. `LocalStorage` needs to be conditionally defined (Done here https://github.com/rehooks/local-storage/pull/61)

Unfortunately with regards to the [rolledup](https://github.com/jharrilim/rolledup) project, well... it was easy to prove that you could build a node environment pre-renderer that used browser globals, but creating an alternative to Gatsby takes a lot more work 😅

**Comment by emateu** [comment]
This might help: https://github.com/rehooks/local-storage/pull/80

**Comment by trevorblades** [comment]
Now that #80 is merged, when can we expect a new version to be published? @jharrilim

**Comment by iamsolankiamit** [comment]
@trevorblades 2.4.4 version has the fix for SSR.
