### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by mateja176** [rehooks/local-storage#72]
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
```

Could this be related to the `devDependencies`:

```json
  "devDependencies": {
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-typescript": "^7.3.3",
    "@testing-library/react": "^8.0.1",
    "@types/jest": "^24.0.13",
    "@types/react": "^16.8.19",
    "all-contributors-cli": "^6.11.2",
    "babel-jest": "^24.8.0",
    "browser-env": "^3.2.6",
    "jest": "^24.8.0",
    "parcel": "^1.12.4",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-hooks-testing-library": "^0.5.1",
    "react-test-renderer": "^16.8.6",
    "ts-jest": "^24.0.2",
    "typedoc": "^0.15.3",
    "typescript": "^3.5.1"
  },
```

To be mroe precise:

```json
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
```

**Comment by jharrilim** [comment]
Hey there! Sorry for seeing this so late. This would not be an issue with our dev dependencies. Dev dependencies don't get installed to your repository when you do `npm install @rehooks/local-storage` (or any module for that matter). The dev dependencies will only be used when you clone our repo, and run `npm install`. Hope this clears up any confusion!

You can learn more a bit more here (albeit I don't feel like they state the above clear enough): https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

## Bonus tidbit

If you noticed, our [package.json](https://github.com/rehooks/local-storage/blob/master/package.json) has a peerDependencies section:

https://github.com/rehooks/local-storage/blob/7b83c40a88fea20d0eaea939903181594fd237f2/package.json#L38-L40

We have to put this here because we don't ship our module with React (our React is in dev dependencies, so you won't get it when you install our module). By putting it in peer dependencies, we say, "we don't ship our code with react, however, you will need to install react (a version greater than or equal to 16.8.0) in order to use our module".
